# Build stage
FROM golang:1.19 AS build

WORKDIR /app

# Copy the services directory
COPY services/user/ /app/user/
COPY app.env /app/user

# Download dependencies from the pkg directory
COPY services/pkg/ /app/pkg/

# Build the application
WORKDIR /app/user
RUN go mod download
RUN go build -o /app/service.user main.go

# Final stage
FROM debian:buster-slim AS run
# Copy the executable
COPY --from=build /app/service.user .
COPY  --from=build  /app/user/app.env . 

# Define the command to run the executable
CMD ["/service.user"]