// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/protobuf/auth.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignInRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae1dfb543efc5a, []int{0}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae1dfb543efc5a, []int{1}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type CheckTokenRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckTokenRequest) Reset()         { *m = CheckTokenRequest{} }
func (m *CheckTokenRequest) String() string { return proto.CompactTextString(m) }
func (*CheckTokenRequest) ProtoMessage()    {}
func (*CheckTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae1dfb543efc5a, []int{2}
}

func (m *CheckTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTokenRequest.Unmarshal(m, b)
}
func (m *CheckTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTokenRequest.Marshal(b, m, deterministic)
}
func (m *CheckTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTokenRequest.Merge(m, src)
}
func (m *CheckTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CheckTokenRequest.Size(m)
}
func (m *CheckTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTokenRequest proto.InternalMessageInfo

func (m *CheckTokenRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type CheckTokenResponse struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckTokenResponse) Reset()         { *m = CheckTokenResponse{} }
func (m *CheckTokenResponse) String() string { return proto.CompactTextString(m) }
func (*CheckTokenResponse) ProtoMessage()    {}
func (*CheckTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae1dfb543efc5a, []int{3}
}

func (m *CheckTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTokenResponse.Unmarshal(m, b)
}
func (m *CheckTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTokenResponse.Marshal(b, m, deterministic)
}
func (m *CheckTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTokenResponse.Merge(m, src)
}
func (m *CheckTokenResponse) XXX_Size() int {
	return xxx_messageInfo_CheckTokenResponse.Size(m)
}
func (m *CheckTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTokenResponse proto.InternalMessageInfo

func (m *CheckTokenResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type Token struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ID                   uint64   `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae1dfb543efc5a, []int{4}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Token) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Token) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func init() {
	proto.RegisterType((*SignInRequest)(nil), "user.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "user.SignInResponse")
	proto.RegisterType((*CheckTokenRequest)(nil), "user.CheckTokenRequest")
	proto.RegisterType((*CheckTokenResponse)(nil), "user.CheckTokenResponse")
	proto.RegisterType((*Token)(nil), "user.Token")
}

func init() { proto.RegisterFile("api/protobuf/auth.proto", fileDescriptor_d3ae1dfb543efc5a) }

var fileDescriptor_d3ae1dfb543efc5a = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0x4d, 0x4f, 0x83, 0x40,
	0x10, 0x15, 0x84, 0xaa, 0x43, 0x6c, 0xe2, 0xd8, 0xa4, 0x84, 0x13, 0x72, 0xea, 0x89, 0x26, 0x98,
	0xc6, 0x83, 0x27, 0xb4, 0x1e, 0xb8, 0x18, 0x43, 0x3d, 0x79, 0xa3, 0xeb, 0x28, 0xa4, 0x96, 0xc5,
	0x5d, 0x56, 0x7f, 0x82, 0x7f, 0xdb, 0xb8, 0x0b, 0xb6, 0x4d, 0x63, 0xbc, 0xf1, 0x66, 0xde, 0x07,
	0x6f, 0x16, 0xc6, 0x45, 0x53, 0x4d, 0x1b, 0xc1, 0x5b, 0xbe, 0x54, 0x2f, 0xd3, 0x42, 0xb5, 0x65,
	0xac, 0x11, 0x3a, 0x4a, 0x92, 0x88, 0x52, 0x38, 0x5d, 0x54, 0xaf, 0x75, 0x56, 0xe7, 0xf4, 0xae,
	0x48, 0xb6, 0x38, 0x02, 0xf7, 0x6e, 0x5d, 0x54, 0x6f, 0xbe, 0x15, 0x5a, 0x93, 0x93, 0xdc, 0x00,
	0x0c, 0xe0, 0xf8, 0xa1, 0x90, 0xf2, 0x93, 0x8b, 0x67, 0xdf, 0xd6, 0x8b, 0x5f, 0x1c, 0x25, 0x30,
	0xec, 0x2d, 0x64, 0xc3, 0x6b, 0x49, 0x18, 0x82, 0x97, 0x32, 0x46, 0x52, 0x3e, 0xf2, 0x15, 0xd5,
	0x9d, 0xd3, 0xf6, 0x28, 0x9a, 0xc1, 0xd9, 0x6d, 0x49, 0x6c, 0xa5, 0x51, 0x1f, 0xfd, 0xbf, 0xec,
	0x0a, 0x70, 0x5b, 0xd6, 0xc5, 0x5d, 0x80, 0xbb, 0x51, 0x78, 0x89, 0x17, 0xff, 0x34, 0x8b, 0x0d,
	0xc7, 0x6c, 0xa2, 0xb4, 0xa3, 0xfc, 0x51, 0x0f, 0xc1, 0xb9, 0x2f, 0xd6, 0xd4, 0x55, 0xd3, 0xdf,
	0x38, 0x04, 0x3b, 0x9b, 0xfb, 0x87, 0xa1, 0x35, 0x71, 0x72, 0x3b, 0x9b, 0x27, 0x5f, 0x16, 0x78,
	0xa9, 0x6a, 0xcb, 0x05, 0x89, 0x8f, 0x8a, 0x11, 0xce, 0x60, 0x60, 0x6a, 0xe3, 0xb9, 0x09, 0xdc,
	0xb9, 0x63, 0x30, 0xda, 0x1d, 0x9a, 0x5f, 0x8d, 0x0e, 0x30, 0x05, 0xd8, 0x54, 0xc0, 0xb1, 0x61,
	0xed, 0xdd, 0x22, 0xf0, 0xf7, 0x17, 0xbd, 0xc5, 0xcd, 0xd1, 0x93, 0x1b, 0x5f, 0x8b, 0x86, 0x2d,
	0x07, 0xfa, 0x25, 0x2f, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x49, 0x2a, 0x66, 0xfc, 0xe4, 0x01,
	0x00, 0x00,
}
