// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package initilizer

import (
	"context"
	"github.com/sajjad1993/todo/pkg/log"
	"github.com/sajjad1993/todo/pkg/meesage_broker"
	"github.com/sajjad1993/todo/services/gateway/adapter/auth_client"
	"github.com/sajjad1993/todo/services/gateway/adapter/broker"
	"github.com/sajjad1993/todo/services/gateway/adapter/broker/consumer/command_handlers"
	"github.com/sajjad1993/todo/services/gateway/adapter/todo_list_client"
	"github.com/sajjad1993/todo/services/gateway/app"
	"github.com/sajjad1993/todo/services/gateway/app/command"
	"github.com/sajjad1993/todo/services/gateway/app/query"
	"github.com/sajjad1993/todo/services/gateway/config"
	"github.com/sajjad1993/todo/services/gateway/container"
	"github.com/sajjad1993/todo/services/gateway/infrastructure/restapi/handlers"
)

// Injectors from wire.go:

// InitializeContainer  is dependency injected form of having *service.Container
func InitializeContainer(ctx context.Context) (*container.Container, error) {
	logger := log.NewLogger()
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	meesage_brokerConfig := config.NewMessageBrokerConfig(configConfig)
	producer, err := meesage_broker.NewProducer(meesage_brokerConfig)
	if err != nil {
		return nil, err
	}
	commandPublisher := broker.New(producer)
	signUp := command.NewSignUpCommand(commandPublisher)
	createTodo := command.NewCreateTodoCommand(commandPublisher)
	createTodoList := command.NewCreateTodoListCommand(commandPublisher)
	updateTodoList := command.NewUpdateTodoListCommand(commandPublisher)
	deleteTodoList := command.NewDeleteTodoListCommand(commandPublisher)
	updateTodo := command.NewUpdateTodoCommand(commandPublisher)
	deleteTodo := command.NewDeleteTodoCommand(commandPublisher)
	commands := app.NewCommands(signUp, createTodo, createTodoList, updateTodoList, deleteTodoList, updateTodo, deleteTodo)
	repository, err := auth_client.New(logger, configConfig)
	if err != nil {
		return nil, err
	}
	signIn := query.NewSignInQuery(repository)
	checkToken := query.NewCheckTokenQuery(repository)
	reader, err := todo_list_client.New(logger, configConfig)
	if err != nil {
		return nil, err
	}
	listToDoList := query.NewListToDoList(reader)
	queries := app.NewQueries(signIn, checkToken, listToDoList)
	application := app.New(commands, queries)
	handler := handlers.NewHandler(application)
	consumer, err := meesage_broker.NewConsumer(meesage_brokerConfig)
	if err != nil {
		return nil, err
	}
	commandsHandlers, err := command_handlers.New(logger, consumer, signUp, createTodoList, createTodo, deleteTodoList, deleteTodo, updateTodoList, updateTodo)
	if err != nil {
		return nil, err
	}
	containerContainer, err := container.NewContainer(logger, configConfig, application, commandPublisher, producer, handler, commandsHandlers)
	if err != nil {
		return nil, err
	}
	return containerContainer, nil
}
