// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/protobuf/todo_list.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListTodoListRequest struct {
	UserID               uint64   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTodoListRequest) Reset()         { *m = ListTodoListRequest{} }
func (m *ListTodoListRequest) String() string { return proto.CompactTextString(m) }
func (*ListTodoListRequest) ProtoMessage()    {}
func (*ListTodoListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85a2c3e2c540a1dd, []int{0}
}

func (m *ListTodoListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTodoListRequest.Unmarshal(m, b)
}
func (m *ListTodoListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTodoListRequest.Marshal(b, m, deterministic)
}
func (m *ListTodoListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTodoListRequest.Merge(m, src)
}
func (m *ListTodoListRequest) XXX_Size() int {
	return xxx_messageInfo_ListTodoListRequest.Size(m)
}
func (m *ListTodoListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTodoListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTodoListRequest proto.InternalMessageInfo

func (m *ListTodoListRequest) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type ListTodoListResponse struct {
	TodoLists            []*TodoList `protobuf:"bytes,1,rep,name=TodoLists,proto3" json:"TodoLists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListTodoListResponse) Reset()         { *m = ListTodoListResponse{} }
func (m *ListTodoListResponse) String() string { return proto.CompactTextString(m) }
func (*ListTodoListResponse) ProtoMessage()    {}
func (*ListTodoListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85a2c3e2c540a1dd, []int{1}
}

func (m *ListTodoListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTodoListResponse.Unmarshal(m, b)
}
func (m *ListTodoListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTodoListResponse.Marshal(b, m, deterministic)
}
func (m *ListTodoListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTodoListResponse.Merge(m, src)
}
func (m *ListTodoListResponse) XXX_Size() int {
	return xxx_messageInfo_ListTodoListResponse.Size(m)
}
func (m *ListTodoListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTodoListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTodoListResponse proto.InternalMessageInfo

func (m *ListTodoListResponse) GetTodoLists() []*TodoList {
	if m != nil {
		return m.TodoLists
	}
	return nil
}

type TodoList struct {
	Name                 string      `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string      `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	TodoItems            []*TodoItem `protobuf:"bytes,3,rep,name=TodoItems,proto3" json:"TodoItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TodoList) Reset()         { *m = TodoList{} }
func (m *TodoList) String() string { return proto.CompactTextString(m) }
func (*TodoList) ProtoMessage()    {}
func (*TodoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_85a2c3e2c540a1dd, []int{2}
}

func (m *TodoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoList.Unmarshal(m, b)
}
func (m *TodoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoList.Marshal(b, m, deterministic)
}
func (m *TodoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoList.Merge(m, src)
}
func (m *TodoList) XXX_Size() int {
	return xxx_messageInfo_TodoList.Size(m)
}
func (m *TodoList) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoList.DiscardUnknown(m)
}

var xxx_messageInfo_TodoList proto.InternalMessageInfo

func (m *TodoList) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TodoList) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TodoList) GetTodoItems() []*TodoItem {
	if m != nil {
		return m.TodoItems
	}
	return nil
}

type TodoItem struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Priority             uint64   `protobuf:"varint,2,opt,name=Priority,proto3" json:"Priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoItem) Reset()         { *m = TodoItem{} }
func (m *TodoItem) String() string { return proto.CompactTextString(m) }
func (*TodoItem) ProtoMessage()    {}
func (*TodoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_85a2c3e2c540a1dd, []int{3}
}

func (m *TodoItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoItem.Unmarshal(m, b)
}
func (m *TodoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoItem.Marshal(b, m, deterministic)
}
func (m *TodoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoItem.Merge(m, src)
}
func (m *TodoItem) XXX_Size() int {
	return xxx_messageInfo_TodoItem.Size(m)
}
func (m *TodoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoItem.DiscardUnknown(m)
}

var xxx_messageInfo_TodoItem proto.InternalMessageInfo

func (m *TodoItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TodoItem) GetPriority() uint64 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func init() {
	proto.RegisterType((*ListTodoListRequest)(nil), "todo_list.ListTodoListRequest")
	proto.RegisterType((*ListTodoListResponse)(nil), "todo_list.ListTodoListResponse")
	proto.RegisterType((*TodoList)(nil), "todo_list.TodoList")
	proto.RegisterType((*TodoItem)(nil), "todo_list.TodoItem")
}

func init() { proto.RegisterFile("api/protobuf/todo_list.proto", fileDescriptor_85a2c3e2c540a1dd) }

var fileDescriptor_85a2c3e2c540a1dd = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xad, 0xeb, 0xe6, 0xfa, 0xea, 0xe9, 0x6d, 0x48, 0x19, 0xa2, 0xa5, 0xa7, 0x5d, 0xec,
	0x70, 0x1e, 0xf5, 0x24, 0xbb, 0x14, 0x44, 0x34, 0xce, 0x8b, 0x17, 0xdd, 0xba, 0x08, 0x81, 0x6d,
	0x89, 0x79, 0x6f, 0x82, 0xff, 0xbd, 0x34, 0xb5, 0x3f, 0x84, 0xed, 0x94, 0x7c, 0x7f, 0x84, 0x0f,
	0x7c, 0x03, 0xe7, 0x0b, 0xa3, 0x26, 0xc6, 0x6a, 0xd6, 0xcb, 0xdd, 0xe7, 0x84, 0xf5, 0x4a, 0xbf,
	0xaf, 0x15, 0x71, 0xea, 0x2c, 0x0c, 0x6a, 0x23, 0xb9, 0x82, 0xc1, 0x83, 0x22, 0x9e, 0xeb, 0x95,
	0x2e, 0x4e, 0x21, 0xbf, 0x76, 0x92, 0x18, 0xcf, 0xa0, 0xf7, 0x4a, 0xd2, 0x66, 0xb3, 0xc8, 0x8b,
	0xbd, 0xb1, 0x2f, 0xfe, 0x54, 0x92, 0xc1, 0xf0, 0x7f, 0x9d, 0x8c, 0xde, 0x92, 0xc4, 0x6b, 0x08,
	0x2a, 0x8f, 0x22, 0x2f, 0xee, 0x8c, 0xc3, 0xe9, 0x20, 0x6d, 0xb0, 0x75, 0xbf, 0x69, 0x25, 0x04,
	0xfd, 0x4a, 0x20, 0x82, 0xff, 0xb8, 0xd8, 0x48, 0x07, 0x0b, 0x84, 0xbb, 0x63, 0x0c, 0xe1, 0x4c,
	0x52, 0x6e, 0x95, 0x61, 0xa5, 0xb7, 0xd1, 0xb1, 0x8b, 0xda, 0x56, 0x05, 0xcd, 0x58, 0x6e, 0x28,
	0xea, 0xec, 0x85, 0x16, 0x99, 0x68, 0x5a, 0xc9, 0x5d, 0x09, 0x2d, 0x04, 0x0e, 0xa1, 0x3b, 0x57,
	0xbc, 0xae, 0xa8, 0xa5, 0xc0, 0x11, 0xf4, 0x9f, 0xac, 0xd2, 0x56, 0xf1, 0x8f, 0x63, 0xfa, 0xa2,
	0xd6, 0xd3, 0x0f, 0x08, 0x8b, 0xd7, 0x2f, 0xd2, 0x7e, 0xab, 0x5c, 0xe2, 0x33, 0x9c, 0xb6, 0xc7,
	0xc0, 0x8b, 0x16, 0x7c, 0xcf, 0xa8, 0xa3, 0xcb, 0x83, 0x79, 0xb9, 0x62, 0x72, 0x74, 0x7f, 0xf2,
	0xd6, 0x4d, 0x6f, 0xad, 0xc9, 0x97, 0x3d, 0xf7, 0x53, 0x37, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xa8, 0x49, 0x7e, 0xb1, 0xc9, 0x01, 0x00, 0x00,
}
