// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package initilizer

import (
	"context"
	"github.com/sajjad1993/todo/internal/common/publisher"
	"github.com/sajjad1993/todo/internal/user/adapter/broker/command_handlers"
	"github.com/sajjad1993/todo/internal/user/adapter/grpc"
	"github.com/sajjad1993/todo/internal/user/adapter/reposiroty/orm"
	"github.com/sajjad1993/todo/internal/user/app"
	"github.com/sajjad1993/todo/internal/user/config"
	"github.com/sajjad1993/todo/internal/user/container"
	"github.com/sajjad1993/todo/pkg/db"
	"github.com/sajjad1993/todo/pkg/log"
	"github.com/sajjad1993/todo/pkg/meesage_broker"
)

// Injectors from wire.go:

// InitializeContainer  is dependency injected form of having *service.Container
func InitializeContainer(ctx context.Context) (*container.Container, error) {
	logger := log.NewLogger()
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	dbConfig := config.NewDatabaseConfig(configConfig)
	gormDB, err := db.NewDb(dbConfig)
	if err != nil {
		return nil, err
	}
	repository := orm.NewUserRepository(gormDB)
	useCase := app.NewService(repository)
	meesage_brokerConfig := config.NewMessageBrokerConfig(configConfig)
	consumer, err := meesage_broker.NewConsumer(meesage_brokerConfig)
	if err != nil {
		return nil, err
	}
	handler := grpc.New(useCase, logger)
	producer, err := meesage_broker.NewProducer(meesage_brokerConfig)
	if err != nil {
		return nil, err
	}
	commandPublisher := publisher.New(producer)
	signUpHandler := command_handlers.NewSignUpCommandHandler(consumer, useCase, logger, commandPublisher)
	commandsHandler, err := command_handlers.New(signUpHandler, logger)
	if err != nil {
		return nil, err
	}
	containerContainer, err := container.NewContainer(logger, configConfig, useCase, repository, consumer, handler, commandsHandler, gormDB)
	if err != nil {
		return nil, err
	}
	return containerContainer, nil
}
